### ISSUE TITLE
Facebook-iOS-SDK file formatter problem

### ISSUE THREAD

**Issue by JGINGIT** [CocoaPods/Specs#12928]
```
-> Installing Facebook-iOS-SDK (3.22.0)
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/facebook/facebook-ios-sdk.git
     /Users/JG/Dropbox/Apps/Wheex/Pods/Facebook-iOS-SDK --single-branch --depth
     1 --branch sdk-version-3.22.0
     Cloning into '/Users/JG/Dropbox/Apps/Wheex/Pods/Facebook-iOS-SDK'...
     Note: checking out 'ed9b79c94da815df72a0b345251ae65087f60755'.
     
     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by performing another checkout.
     
     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -b with the checkout command again. Example:
     
       git checkout -b new_branch_name
     
 > Running prepare command
   $ /bin/bash  set -e find src -name \*.png | grep -v @ | grep -v '/tests/' |
   grep -v 'Tests/' | grep -v -- - | sed -e
   's|\(.*\)/\([a-zA-Z0-9]*\).png|scripts/image_to_code.py -i \1/\2.png -c \2
   -o src/ImageResources|' | sh && find src -name \*.wav | grep -v @ | grep -v
   -- - | sed -e 's|\(.*\)/\([a-zA-Z0-9]*\).wav|scripts/audio_to_code.py -i
   \1/\2.wav -c \2 -o src/AudioResources|' | sh
   sh: scripts/image_to_code.py: /usr/bin/python^M: bad interpreter: No such file or directory
   sh: scripts/image_to_code.py: /usr/bin/python^M: bad interpreter: No such file or directory
   sh: scripts/image_to_code.py: /usr/bin/python^M: bad interpreter: No such file or directory
   sh: scripts/image_to_code.py: /usr/bin/python^M: bad interpreter: No such file or directory
   sh: scripts/image_to_code.py: /usr/bin/python^M: bad interpreter: No such file or directory
   sh: scripts/image_to_code.py: /usr/bin/python^M: bad interpreter: No such file or directory
   sh: scripts/image_to_code.py: /usr/bin/python^M: bad interpreter: No such file or directory
   sh: scripts/image_to_code.py: /usr/bin/python^M: bad interpreter: No such file or directory
   sh: scripts/image_to_code.py: /usr/bin/python^M: bad interpreter: No such file or directory
   sh: scripts/image_to_code.py: /usr/bin/python^M: bad interpreter: No such file or directory
   sh: scripts/image_to_code.py: /usr/bin/python^M: bad interpreter: No such file or directory
[!] /bin/bash 
set -e
find src -name \*.png | grep -v @ | grep -v '/tests/' | grep -v 'Tests/' | grep -v -- - | sed -e 's|\(.*\)/\([a-zA-Z0-9]*\).png|scripts/image_to_code.py -i \1/\2.png -c \2 -o src/ImageResources|' | sh && find src -name \*.wav | grep -v @ | grep -v -- - | sed -e 's|\(.*\)/\([a-zA-Z0-9]*\).wav|scripts/audio_to_code.py -i \1/\2.wav -c \2 -o src/AudioResources|' | sh

sh: scripts/image_to_code.py: /usr/bin/python^M: bad interpreter: No such file or directory

sh: scripts/image_to_code.py: /usr/bin/python^M: bad interpreter: No such file or directory

sh: scripts/image_to_code.py: /usr/bin/python^M: bad interpreter: No such file or directory

sh: scripts/image_to_code.py: /usr/bin/python^M: bad interpreter: No such file or directory

sh: scripts/image_to_code.py: /usr/bin/python^M: bad interpreter: No such file or directory

sh: scripts/image_to_code.py: /usr/bin/python^M: bad interpreter: No such file or directory

sh: scripts/image_to_code.py: /usr/bin/python^M: bad interpreter: No such file or directory

sh: scripts/image_to_code.py: /usr/bin/python^M: bad interpreter: No such file or directory

sh: scripts/image_to_code.py: /usr/bin/python^M: bad interpreter: No such file or directory

sh: scripts/image_to_code.py: /usr/bin/python^M: bad interpreter: No such file or directory

sh: scripts/image_to_code.py: /usr/bin/python^M: bad interpreter: No such file or directory


/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/executable.rb:70:in `execute_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/executable.rb:27:in `block in executable'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer/pod_source_installer.rb:127:in `block (2 levels) in run_prepare_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer/pod_source_installer.rb:123:in `chdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer/pod_source_installer.rb:123:in `block in run_prepare_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer/pod_source_installer.rb:122:in `run_prepare_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer/pod_source_installer.rb:46:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:298:in `install_source_of_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:273:in `block (2 levels) in install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/user_interface.rb:70:in `titled_section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:272:in `block in install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:264:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:264:in `install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:116:in `block in download_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:114:in `download_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:91:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:271:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command.rb:45:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/bin/pod:43:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```
and there is same issue https://github.com/CocoaPods/CocoaPods/issues/2418 
I can't slove it by doing
```
sudo ln -s /usr/bin/python /usr/bin/python^M
```
I can run 'python^M'  but there is still  ' bad interpreter ' when 'pod install'
Any suggestions?

**Comment by JGINGIT** [comment]
```
sudo ln -s /usr/bin/python /usr/bin/python^M
```
and then
```
sudo mv /usr/bin/python^M  /usr/bin/python$'\r'
```
it works

**Comment by Keithbsmiley** [comment]
:+1:
